#ifndef __ARTEFACT_ITEM_ENUM_H__
#define __ARTEFACT_ITEM_ENUM_H__

// Last Saved,#2005-08-11 15:17:29#,"Lionhead Studios Ltd"

//*****************************************************************************
// ENUM Values: ARTEFACT
//*****************************************************************************
enum     ARTEFACT
{
    ARTEFACT_FIRST                                  =  0 ,
    ARTEFACT_ABODE_NUMBER_A                         =  0 ,
    ARTEFACT_ABODE_NUMBER_B                         =  1 ,
    ARTEFACT_ABODE_NUMBER_C                         =  2 ,
    ARTEFACT_ABODE_NUMBER_D                         =  3 ,
    ARTEFACT_ABODE_NUMBER_E                         =  4 ,
    ARTEFACT_ABODE_NUMBER_SKYSCRAPER                =  5 ,
    ARTEFACT_ABODE_NUMBER_ALTAR                     =  6 ,
    ARTEFACT_ABODE_NUMBER_STORAGE_PIT               =  7 ,
    ARTEFACT_ABODE_NUMBER_CRECHE                    =  8 ,
    ARTEFACT_ABODE_NUMBER_SHRINE                    =  9 ,
    ARTEFACT_ABODE_NUMBER_TEMPLE                    =  10 ,
    ARTEFACT_ABODE_NUMBER_PUB                       =  11 ,
    ARTEFACT_ABODE_NUMBER_TOWN_CENTRE               =  12 ,
    ARTEFACT_ABODE_NUMBER_CREATURE_PEN              =  13 ,
    ARTEFACT_ABODE_NUMBER_FIELD                     =  14 ,
    ARTEFACT_ABODE_NUMBER_MELEE_ARMOURY             =  15 ,
    ARTEFACT_ABODE_NUMBER_RANGED_ARMOURY            =  16 ,
    ARTEFACT_ABODE_NUMBER_WORKSHOP                  =  17 ,
    ARTEFACT_ABODE_NUMBER_STUDY                     =  18 ,
    ARTEFACT_ABODE_NUMBER_UNIVERSITY                =  19 ,
    ARTEFACT_ABODE_NUMBER_PRISON                    =  20 ,
    ARTEFACT_ABODE_NUMBER_SMELTER                   =  21 ,
    ARTEFACT_ABODE_NUMBER_GRANARY                   =  22 ,
    ARTEFACT_ABODE_NUMBER_LUMBERMILL                =  23 ,
    ARTEFACT_ABODE_NUMBER_MARKET_POT                =  24 ,
    ARTEFACT_ABODE_NUMBER_MARKET_STATUE             =  25 ,
    ARTEFACT_ABODE_NUMBER_MARKET_PLANT              =  26 ,
    ARTEFACT_ABODE_NUMBER_AMPITHEATRE               =  27 ,
    ARTEFACT_ABODE_NUMBER_GRAVEYARD                 =  28 ,
    ARTEFACT_ABODE_NUMBER_OLD_PERSONS_HOME          =  29 ,
    ARTEFACT_ABODE_NUMBER_BATHHOUSE                 =  30 ,
    ARTEFACT_ABODE_NUMBER_WALLTOWER_TECH0           =  31 ,
    ARTEFACT_ABODE_NUMBER_WALLTOWER_TECH1           =  32 ,
    ARTEFACT_ABODE_NUMBER_GATEHOUSE                 =  33 ,
    ARTEFACT_ABODE_NUMBER_GATEHOUSE_F               =  34 ,
    ARTEFACT_EPIC_WONDER_NUMBER_HURRICANE           =  35 ,
    ARTEFACT_EPIC_WONDER_NUMBER_EARTHQUAKE          =  36 ,
    ARTEFACT_EPIC_WONDER_NUMBER_VOLCANO             =  37 ,
    ARTEFACT_EPIC_WONDER_NUMBER_VERDANT             =  38 ,
    ARTEFACT_EPIC_WONDER_NUMBER_STOPTIME            =  39 ,
    ARTEFACT_EPIC_WONDER_NUMBER_SIREN               =  40 ,
    ARTEFACT_EPIC_WONDER_NUMBER_WOMD                =  41 ,
    ARTEFACT_MAGIC_TYPE_LIFE_HEAL                   =  42 ,
    ARTEFACT_MAGIC_TYPE_LIFE_LIFE                   =  43 ,
    ARTEFACT_MAGIC_TYPE_DEATH_DECAY                 =  44 ,
    ARTEFACT_MAGIC_TYPE_DEATH_DEATH                 =  45 ,
    ARTEFACT_MAGIC_TYPE_FIRE_FIRE                   =  46 ,
    ARTEFACT_MAGIC_TYPE_FIRE_LAVA                   =  47 ,
    ARTEFACT_MAGIC_TYPE_EARTH_TREMOR                =  48 ,
    ARTEFACT_MAGIC_TYPE_EARTH_METEOR                =  49 ,
    ARTEFACT_MAGIC_TYPE_AIR_WIND                    =  50 ,
    ARTEFACT_MAGIC_TYPE_AIR_TEMPEST                 =  51 ,
    ARTEFACT_MAGIC_TYPE_WATER_RAIN                  =  52 ,
    ARTEFACT_MAGIC_TYPE_WATER_STORM                 =  53 ,
    ARTEFACT_CREATURE_MAGIC_TYPE_HEAL               =  54 ,
    ARTEFACT_CREATURE_MAGIC_TYPE_WATER              =  55 ,
    ARTEFACT_CREATURE_MAGIC_TYPE_FIREBALL           =  56 ,
    ARTEFACT_CREATURE_MAGIC_TYPE_LIGHTNING          =  57 ,
    ARTEFACT_CREATURE_TOY_GOOD                      =  58 ,
    ARTEFACT_CREATURE_TOY_NEUTRAL                   =  59 ,
    ARTEFACT_CREATURE_TOY_EVIL                      =  60 ,
    ARTEFACT_CREATURE_ROLE_BUILDER_1                =  61 ,
    ARTEFACT_CREATURE_ROLE_BUILDER_2                =  62 ,
    ARTEFACT_CREATURE_ROLE_BUILDER_3                =  63 ,
    ARTEFACT_CREATURE_ROLE_BUILDER_4                =  64 ,
    ARTEFACT_CREATURE_ROLE_GATHERER_1               =  65 ,
    ARTEFACT_CREATURE_ROLE_GATHERER_2               =  66 ,
    ARTEFACT_CREATURE_ROLE_GATHERER_3               =  67 ,
    ARTEFACT_CREATURE_ROLE_GATHERER_4               =  68 ,
    ARTEFACT_CREATURE_ROLE_SOLDIER_1                =  69 ,
    ARTEFACT_CREATURE_ROLE_SOLDIER_2                =  70 ,
    ARTEFACT_CREATURE_ROLE_SOLDIER_3                =  71 ,
    ARTEFACT_CREATURE_ROLE_SOLDIER_4                =  72 ,
    ARTEFACT_CREATURE_ROLE_ENTERTAINER_1            =  73 ,
    ARTEFACT_CREATURE_ROLE_ENTERTAINER_2            =  74 ,
    ARTEFACT_CREATURE_ROLE_ENTERTAINER_3            =  75 ,
    ARTEFACT_CREATURE_ROLE_ENTERTAINER_4            =  76 ,
    ARTEFACT_EMBELLISHMENT_INFO_AZTEC_FOUNTAIN      =  77 ,
    ARTEFACT_EMBELLISHMENT_INFO_AZTEC_FOUNTAIN_GOOD =  78 ,
    ARTEFACT_EMBELLISHMENT_INFO_AZTEC_FOUNTAIN_EVIL =  79 ,
    ARTEFACT_EMBELLISHMENT_INFO_AZTEC_STATUE        =  80 ,
    ARTEFACT_EMBELLISHMENT_INFO_AZTEC_STATUE_GOOD   =  81 ,
    ARTEFACT_EMBELLISHMENT_INFO_AZTEC_STATUE_EVIL   =  82 ,
    ARTEFACT_EMBELLISHMENT_INFO_JAPANESE_FOUNTAIN   =  83 ,
    ARTEFACT_EMBELLISHMENT_INFO_JAPANESE_FOUNTAIN_GOOD
                                                    =  84 ,
    ARTEFACT_EMBELLISHMENT_INFO_JAPANESE_FOUNTAIN_EVIL
                                                    =  85 ,
    ARTEFACT_EMBELLISHMENT_INFO_JAPANESE_SHRINE     =  86 ,
    ARTEFACT_EMBELLISHMENT_INFO_JAPANESE_SHRINE_GOOD=  87 ,
    ARTEFACT_EMBELLISHMENT_INFO_JAPANESE_SHRINE_EVIL=  88 ,
    ARTEFACT_EMBELLISHMENT_INFO_JAPANESE_GARDEN     =  89 ,
    ARTEFACT_EMBELLISHMENT_INFO_JAPANESE_GARDEN_EVIL=  90 ,
    ARTEFACT_EMBELLISHMENT_INFO_NORSE_FOUNTAIN      =  91 ,
    ARTEFACT_EMBELLISHMENT_INFO_NORSE_FOUNTAIN_GOOD =  92 ,
    ARTEFACT_EMBELLISHMENT_INFO_NORSE_FOUNTAIN_EVIL =  93 ,
    ARTEFACT_EMBELLISHMENT_INFO_NORSE_STATUE        =  94 ,
    ARTEFACT_EMBELLISHMENT_INFO_NORSE_STATUE_GOOD   =  95 ,
    ARTEFACT_EMBELLISHMENT_INFO_NORSE_STATUE_EVIL   =  96 ,
    ARTEFACT_EMBELLISHMENT_INFO_GREEK_FERTILITY_STATUE
                                                    =  97 ,
    ARTEFACT_EMBELLISHMENT_INFO_GREEK_FOUNTAIN      =  98 ,
    ARTEFACT_EMBELLISHMENT_INFO_GREEK_STREETLAMP    =  99 ,
    ARTEFACT_EMBELLISHMENT_INFO_GREEK_TORTURE_PIT   =  100 ,
    ARTEFACT_EMBELLISHMENT_INFO_GREEK_COLUMN        =  101 ,
    ARTEFACT_EMBELLISHMENT_INFO_GREEK_GARDEN        =  102 ,
    ARTEFACT_EMBELLISHMENT_INFO_GREEK_WELL          =  103 ,
    ARTEFACT_EMBELLISHMENT_INFO_GREEK_SPIKE         =  104 ,
    ARTEFACT_EMBELLISHMENT_INFO_GREEK_MIRACLE_ENHANCER
                                                    =  105 ,
    ARTEFACT_HAND_MULTIPICKUP                       =  106 ,
    ARTEFACT_HAND_FISTING                           =  107 ,
    ARTEFACT_HAND_GESTURES                          =  108 ,
    ARTEFACT_LASTLAND_ONE_MAN                       =  109 ,
    ARTEFACT_LASTLAND_ONE_WOMAN                     =  110 ,
    ARTEFACT_LASTLAND_HUNDRED_SOLDIERS              =  111 ,
    ARTEFACT_LASTLAND_HUNDRED_ARCHERS               =  112 ,
    ARTEFACT_LASTLAND_SIEGE_ENGINE                  =  113 ,
    ARTEFACT_TOME_AGE_OF_GODS                       =  114 ,
    ARTEFACT_TOME_BARREN_SEAS                       =  115 ,
    ARTEFACT_TOME_FATE_OF_THE_EGYPTIANS             =  116 ,
    ARTEFACT_TOME_FRAGMENT                          =  117 ,
    ARTEFACT_TOME_GODLESS_MIRACLES                  =  118 ,
    ARTEFACT_TOME_IMMORTAL                          =  119 ,
    ARTEFACT_TOME_MISSIONARIES                      =  120 ,
    ARTEFACT_TOME_ORIGIN_OF_CREATURES               =  121 ,
    ARTEFACT_TOME_PARCHMENT                         =  122 ,
    ARTEFACT_TOME_POWER_OF_THE_AZTECS               =  123 ,
    ARTEFACT_TOME_GREEKS                            =  124 ,
    ARTEFACT_TOME_JAPANESE                          =  125 ,
    ARTEFACT_TOME_NORSE                             =  126 ,
    ARTEFACT_TOME_PROPHECY                          =  127 ,
    ARTEFACT_LAST                                   =  128 ,
    ARTEFACT_FIRST_ABODE                            =  0 ,
    ARTEFACT_LAST_ABODE                             =  35 ,
    ARTEFACT_FIRST_EPIC_WONDER                      =  35 ,
    ARTEFACT_LAST_EPIC_WONDER                       =  42 ,
    ARTEFACT_FIRST_MAGIC_TYPE                       =  42 ,
    ARTEFACT_LAST_MAGIC_TYPE                        =  54 ,
    ARTEFACT_FIRST_CREATURE_MAGIC_TYPE              =  54 ,
    ARTEFACT_LAST_CREATURE_MAGIC_TYPE               =  58 ,
    ARTEFACT_FIRST_CREATURE_TOY                     =  58 ,
    ARTEFACT_LAST_CREATURE_TOY                      =  61 ,
    ARTEFACT_FIRST_CREATURE_ROLE                    =  61 ,
    ARTEFACT_LAST_CREATURE_ROLE                     =  77 ,
    ARTEFACT_FIRST_EMBELLISHMENT                    =  77 ,
    ARTEFACT_LAST_EMBELLISHMENT                     =  106 ,
    ARTEFACT_FIRST_TOME                             =  114 ,
    ARTEFACT_LAST_TOME                              =  128 ,
};

#endif    // __ARTEFACT_ITEM_ENUM_H__