#ifndef INCLUSIONGUARD_AUDIOMIXERCHANNELENUM_H
#define INCLUSIONGUARD_AUDIOMIXERCHANNELENUM_H


// When editing this, remember to update GAudioMixer::PopulateChannelEnums() :)
//------------------------------------------------------------------------------------------------------------
enum AUDIO_MIXER_CHANNEL
{
	AUDIO_MIXER_CHANNEL_FIRST = 0,

	//these are the mixers used for assets - sounds can be assigned to these in the bank editor
	AUDIO_MIXER_CHANNEL_ASSET_1 = 0,
	AUDIO_MIXER_CHANNEL_ASSET_2,
	AUDIO_MIXER_CHANNEL_ASSET_3,
	AUDIO_MIXER_CHANNEL_ASSET_4,
	AUDIO_MIXER_CHANNEL_ASSET_5,
	AUDIO_MIXER_CHANNEL_ASSET_6,
	AUDIO_MIXER_CHANNEL_ASSET_7,
	AUDIO_MIXER_CHANNEL_ASSET_8,
	AUDIO_MIXER_CHANNEL_ASSET_9,
	AUDIO_MIXER_CHANNEL_ASSET_10,
	AUDIO_MIXER_CHANNEL_ASSET_11,
	AUDIO_MIXER_CHANNEL_ASSET_12,
	AUDIO_MIXER_CHANNEL_ASSET_13,
	AUDIO_MIXER_CHANNEL_ASSET_14,
	AUDIO_MIXER_CHANNEL_ASSET_15,
	AUDIO_MIXER_CHANNEL_ASSET_16,

	//every audio object should be assigned to one from each of the next three groups of mixers,
	// eg: global + menu_sfx + animation_villager

	//global mixer
	AUDIO_MIXER_CHANNEL_GLOBAL,

	//mixers for the menu
	AUDIO_MIXER_CHANNEL_MENU_SFX,
	AUDIO_MIXER_CHANNEL_MENU_MUSIC,
	AUDIO_MIXER_CHANNEL_MENU_ATMOS,

	//mixers for individual sections
	AUDIO_MIXER_CHANNEL_MUSIC,
	AUDIO_MIXER_CHANNEL_ATMOS_MAP,
	AUDIO_MIXER_CHANNEL_ATMOS_POSITIONAL,
	AUDIO_MIXER_CHANNEL_ANIMATION_VILLAGER,
	AUDIO_MIXER_CHANNEL_ANIMATION_CREATURE,
	AUDIO_MIXER_CHANNEL_SFX,
	AUDIO_MIXER_CHANNEL_SCRIPT_SFX,
	AUDIO_MIXER_CHANNEL_DIALOGUE,
	AUDIO_MIXER_CHANNEL_PHYSICS_SFX,

	//special sections to work around engine limitations - don't tweak these
	AUDIO_MIXER_CHANNEL_SPECIAL_MENU,
	AUDIO_MIXER_CHANNEL_SPECIAL_DIALOGUE,

	//end marker
	AUDIO_MIXER_CHANNEL_LAST = 32
};


#endif //INCLUSIONGUARD_AUDIOMIXERCHANNELENUM_H
