// Creature Animation Header

#ifndef __CREATURE_SPEC_H__
#define __CREATURE_SPEC_H__


#define C_CURRENT_VERSION                29

enum CREATURE_ANIMATIONS
{
	C_MOVE_STAND,                    // 0
	C_MOVE_WALK,                     // 1
	C_MOVE_WALK_ALT1,                // 2
	C_MOVE_WALK_ALT2,                // 3
	C_MOVE_WALK_ALT3,                // 4
	C_MOVE_RUN,                      // 5
	C_MOVE_R_SPIN_90,                // 6
	C_MOVE_R_SPIN_180,               // 7
	C_MOVE_STEP_F,                   // 8
	C_MOVE_STEP_B,                   // 9
	C_MOVE_STAND_POSE,               // 10
	C_MOVE_STAND_POSE_HILL_DOWN,     // 11
	C_MOVE_STAND_POSE_HILL_UP,       // 12
	C_MOVE_STAND_POSE_HILL_SIDE,     // 13
	C_MOVE_WALK_INTO,                // 14
	C_MOVE_WALK_OUTOF,               // 15
	C_MOVE_WALK_STEP90,              // 16
	C_MOVE_WALK_STEP180,             // 17
	C_MOVE_WALK_TURN90,              // 18
	C_MOVE_WALK_TURN180,             // 19
	C_MOVE_RUN_INTO,                 // 20
	C_MOVE_RUN_OUTOF,                // 21
	C_MOVE_RUN_STEP90,               // 22
	C_MOVE_RUN_STEP180,              // 23
	C_MOVE_RUN_TURN90,               // 24
	C_MOVE_RUN_TURN180,              // 25
	C_MOVE_RUN_ANTICIPATION,         // 26
	C_MOVE_STEP_F_SHORT,             // 27
	C_MOVE_JUMP_L,                   // 28
	C_MOVE_STEP_L,                   // 29
	C_FACE_SMILE,                    // 30
	C_FACE_SMILE1,                   // 31
	C_FACE_SMILE2,                   // 32
	C_FACE_GRIMACE,                  // 33
	C_FACE_GROWL,                    // 34
	C_FACE_SCARED,                   // 35
	C_FACE_SAD,                      // 36
	C_FACE_AMAZED,                   // 37
	C_FACE_PUZZLED,                  // 38
	C_FACE_LAUGH,                    // 39
	C_FACE_OOH,                      // 40
	C_FACE_AAH,                      // 41
	C_FACE_EYES_CLOSED,              // 42
	C_FACE_EARSPERKED,               // 43
	C_FACE_EH,                       // 44
	C_STATIC_START_SLEEP,            // 45
	C_STATIC_SLEEP,                  // 46
	C_STATIC_END_SLEEP,              // 47
	C_STATIC_START_POO,              // 48
	C_STATIC_POO,                    // 49
	C_STATIC_END_POO,                // 50
	C_STATIC_START_PUKE,             // 51
	C_STATIC_PUKE,                   // 52
	C_STATIC_END_PUKE,               // 53
	C_STATIC_START_SIT,              // 54
	C_STATIC_SIT,                    // 55
	C_STATIC_END_SIT,                // 56
	C_IDLE_FIDGET01,                 // 57
	C_IDLE_FIDGET02,                 // 58
	C_IDLE_FIDGET03,                 // 59
	C_INDIVIDUAL_SUMMON,             // 60
	C_INDIVIDUAL_ANGRY,              // 61
	C_INDIVIDUAL_ANGRY2,             // 62
	C_INDIVIDUAL_ANGRY3,             // 63
	C_INDIVIDUAL_HUNGRY,             // 64
	C_INDIVIDUAL_HAPPY,              // 65
	C_INDIVIDUAL_HAPPY2,             // 66
	C_INDIVIDUAL_HAPPY3,             // 67
	C_INDIVIDUAL_SAD,                // 68
	C_INDIVIDUAL_SAD2,               // 69
	C_INDIVIDUAL_TIRED,              // 70
	C_INDIVIDUAL_TIRED2,             // 71
	C_INDIVIDUAL_HOT,                // 72
	C_INDIVIDUAL_COLD,               // 73
	C_INDIVIDUAL_SCRATCH,            // 74
	C_INDIVIDUAL_FRIGHTENED,         // 75
	C_INDIVIDUAL_SNEEZE,             // 76
	C_INDIVIDUAL_CONFUSED,           // 77
	C_INDIVIDUAL_IMPRESS,            // 78
	C_INDIVIDUAL_NEED_A_POO,         // 79
	C_INDIVIDUAL_FEEL_PLAYFUL,       // 80
	C_INDIVIDUAL_LOOK_AT_ME,         // 81
	C_INDIVIDUAL_TAUNT,              // 82
	C_INDIVIDUAL_DRINK,              // 83
	C_INDIVIDUAL_FRIENDLY_WAVE,      // 84
	C_INDIVIDUAL_EMBARRASSED,        // 85
	C_INDIVIDUAL_BEING_ELECTRICUTED, // 86
	C_INDIVIDUAL_MEXICAN_WAVE,       // 87
	C_INDIVIDUAL_POINTING_LAUGHING,  // 88
	C_INDIVIDUAL_PULLING_FACES1,     // 89
	C_INDIVIDUAL_PULLING_FACES2,     // 90
	C_INDIVIDUAL_PULLING_FACES3,     // 91
	C_INDIVIDUAL_SHAKEOFF,           // 92
	C_INDIVIDUAL_DONE_IT,            // 93
	C_INDIVIDUAL_BECKONING,          // 94
	C_INDIVIDUAL_EXHAUSTED,          // 95
	C_INDIVIDUAL_EXHAUSTED2,         // 96
	C_INDIVIDUAL_FEARPLAYER,         // 97
	C_INDIVIDUAL_LIKEPLAYER,         // 98
	C_INDIVIDUAL_LOVEPLAYER,         // 99
	C_INDIVIDUAL_NERVOUSPLAYER,      // 100
	C_INDIVIDUAL_TENSEMUSCLES,       // 101
	C_INDIVIDUAL_TRAINING,           // 102
	C_INDIVIDUAL_HEAL,               // 103
	C_LOOK_MOVE_RIGHT_LEFT,          // 104
	C_LOOK_MOVE_DOWN_UP,             // 105
	C_LOOK_SIT_R_L,                  // 106
	C_LOOK_SIT_D_U,                  // 107
	C_LOOK_STAND_RIGHT_LEFT,         // 108
	C_LOOK_STAND_DOWN_UP,            // 109
	C_PICKUP_FRONT_RIGHT,            // 110
	C_PICKUP_FRONT_LEFT,             // 111
	C_PICKUP_BACK_RIGHT,             // 112
	C_PICKUP_BACK_LEFT,              // 113
	C_PICKUP_HOLD,                   // 114
	C_PICKUP_FROM_HAND,              // 115
	C_THROW_HURL_NEAR,               // 116
	C_THROW_HURL_FAR,                // 117
	C_OBJECT_REMOVE_DISCARD,         // 118
	C_OBJECT_REMOVE_EAT,             // 119
	C_OBJECT_REMOVE_PUT_DOWN,        // 120
	C_OBJECT_KEEP_STROKE,            // 121
	C_OBJECT_KEEP_SHAKE,             // 122
	C_OBJECT_KEEP_SMELL,             // 123
	C_OBJECT_KEEP_EXAMINE,           // 124
	C_OBJECT_KEEP_ATTACKVOODOODOLL,  // 125
	C_OBJECT_KEEP_ATTACKVOODOODOLL1, // 126
	C_OBJECT_KEEP_LOVETEDDY,         // 127
	C_OBJECT_KEEP_LOVETEDDY1,        // 128
	C_FIGHT_EXTRA_FAINT,             // 129
	C_FIGHT_EXTRA_GET_UP,            // 130
	C_FIGHT_EXTRA_CREATION,          // 131
	C_FIGHT_EXTRA_REBORN,            // 132
	C_DESTROY_FRONT_RIGHT,           // 133
	C_DESTROY_FRONT_LEFT,            // 134
	C_DESTROY_BACK_RIGHT,            // 135
	C_DESTROY_BACK_LEFT,             // 136
	C_DESTROY_KICK_LOW,              // 137
	C_FIGHT_ATTACK1,                 // 138
	C_FIGHT_ATTACK2,                 // 139
	C_FIGHT_ATTACK3_B_LEFT,          // 140
	C_FIGHT_ATTACK3_B_RIGHT,         // 141
	C_FIGHT_ATTACK3_F_LEFT,          // 142
	C_FIGHT_ATTACK3_F_RIGHT,         // 143
	C_FIGHT_ATTACK4,                 // 144
	C_FIGHT_BRUSHOFF_WEAPONS_ARM,    // 145
	C_FIGHT_BRUSHOFF_WEAPONS_BACK,   // 146
	C_FIGHT_BRUSHOFF_WEAPONS_CHEST,  // 147
	C_FIGHT_BUSTING_THRU_GATES,      // 148
	C_FIGHT_BUSTING_THRU_WALLS,      // 149
	C_FIGHT_FINCHING_ARROWS_ARMS,    // 150
	C_FIGHT_FINCHING_ARROWS_BACK,    // 151
	C_FIGHT_FINCHING_ARROWS_CHEST,   // 152
	C_FIGHT_FINCHING_ARROWS_LEGS,    // 153
	C_FIGHT_HOLDING_INJURIES_ARMS,   // 154
	C_FIGHT_HOLDING_INJURIES_BACK,   // 155
	C_FIGHT_HOLDING_INJURIES_CHEST,  // 156
	C_FIGHT_MULTISTOMP_BACK,         // 157
	C_FIGHT_MULTISTOMP_FRONTLEFT,    // 158
	C_FIGHT_MULTISTOMP_FRONTMID,     // 159
	C_FIGHT_MULTISTOMP_INTO,         // 160
	C_FIGHT_MULTISTOMP_OUTOF,        // 161
	C_FIGHT_OVER_WALLS,              // 162
	C_FIGHT_SHEILDING_TROOPS_SIDE,   // 163
	C_FIGHT_SIGNAL_ARCHES_ATTACK,    // 164
	C_FIGHT_SIGNAL_SWORDSHEILD_ATTACK, // 165
	C_FIGHT_SPITTING_BLOOD,          // 166
	C_FIGHT_SWEEPING_TOP_WALLS_B_HIGH, // 167
	C_FIGHT_SWEEPING_TOP_WALLS_B_LOW, // 168
	C_FIGHT_SWEEPING_TOP_WALLS_F_HIGH, // 169
	C_FIGHT_SWEEPING_TOP_WALLS_F_LOW, // 170
	C_FIGHT_THREAT1,                 // 171
	C_FIGHT_THREAT2,                 // 172
	C_FIGHT_THREAT3,                 // 173
	C_FIGHT_WALLATTACK_HIGH1,        // 174
	C_FIGHT_WALLATTACK_MID1,         // 175
	C_FIGHT_WALLATTACK_LOW1,         // 176
	C_FIGHT_WALLATTACK_TOP1_H,       // 177
	C_FIGHT_WALLATTACK_TOP1_L,       // 178
	C_SPELL_BUILDUP,                 // 179
	C_SPELL_THROW_NEAR,              // 180
	C_SPELL_THROW_FAR,               // 181
	C_SPELL_THROW_PREHIT,            // 182
	C_SPELL_SHOT_INTO,               // 183
	C_SPELL_SHOT_LOOP,               // 184
	C_SPELL_SHOT_OUTOF,              // 185
	C_SPELL_AREA_EFFECT_INTO,        // 186
	C_SPELL_AREA_EFFECT_LOOP,        // 187
	C_SPELL_AREA_EFFECT_OUTOF,       // 188
	C_SPELL_AREA_EFFECT2_INTO,       // 189
	C_SPELL_AREA_EFFECT2_LOOP,       // 190
	C_SPELL_AREA_EFFECT2_OUTOF,      // 191
	C_SPELL_LIGHTNING_INTO,          // 192
	C_SPELL_LIGHTNING_LOOP,          // 193
	C_SPELL_LIGHTNING_OUTOF,         // 194
	C_DANCE_BASIC,                   // 195
	C_DANCE_A,                       // 196
	C_DANCE_B,                       // 197
	C_DANCE_C,                       // 198
	C_DANCE_D,                       // 199
	C_REWARD_HEAD,                   // 200
	C_REWARD_ARMPIT_R,               // 201
	C_REWARD_BELLY,                  // 202
	C_REWARD_GROIN,                  // 203
	C_REWARD_FOOT_R,                 // 204
	C_REWARD_HAND_R,                 // 205
	C_PUNISH_HEAD_SLAP_R,            // 206
	C_PUNISH_WAIST_SLAP_R,           // 207
	C_PUNISH_FEET_SLAP_R,            // 208
	C_PUNISH_HEAD_GENTLE_R,          // 209
	C_PUNISH_WAIST_GENTLE_R,         // 210
	C_PUNISH_FEET_GENTLE_R,          // 211
	C_RECOIL_HI,                     // 212
	C_RECOIL_HI_L,                   // 213
	C_RECOIL_HI_T,                   // 214
	C_RECOIL_HI_B,                   // 215
	C_RECOIL_MI,                     // 216
	C_RECOIL_MI_L,                   // 217
	C_RECOIL_MI_B,                   // 218
	C_RECOIL_LO,                     // 219
	C_RECOIL_LO_L,                   // 220
	C_RECOIL_LO_B,                   // 221
	C_RECOIL_HI_R_L,                 // 222
	C_RECOIL_HI_F_B,                 // 223
	C_RECOIL_LO_R_L,                 // 224
	C_RECOIL_LO_F_B,                 // 225
	C_RECOIL_KNOCKDOWN_SIDE,         // 226
	C_RECOIL_KNOCKDOWN_BACK,         // 227
	C_GATEHOUSE_BRACING_INTO,        // 228
	C_GATEHOUSE_BRACING_LOOP,        // 229
	C_GATEHOUSE_BRACING_OUTOF,       // 230
	C_GATEHOUSE_BRACING_REACTION1,   // 231
	C_GATEHOUSE_BRACING_REACTION2,   // 232
	C_GATEHOUSE_BRACING_KNOCKDOWN,   // 233
	C_GATEHOUSE_BRACING_GETUP,       // 234
	C_CONCURRENT_NOD,                // 235
	C_CONCURRENT_SHAKE,              // 236
	C_CONCURRENT_YAWN,               // 237
	C_POINT_LO_LEFT,                 // 238
	C_POINT_LO_RIGHT,                // 239
	C_POINT_HI_LEFT,                 // 240
	C_POINT_HI_RIGHT,                // 241
	C_MISC_KISS_HI,                  // 242
	C_MISC_KISS_LO,                  // 243
	C_CATCH_STEP_RIGHT,              // 244
	C_CATCH_HI_R,                    // 245
	C_CATCH_HI_L,                    // 246
	C_CATCH_LO_R,                    // 247
	C_CATCH_LO_L,                    // 248
	C_CATCH_FLINCH,                  // 249
	C_CREATUREFIGHT_ATTACK_INTO,     // 250
	C_CREATUREFIGHT_ATTACKPOSE_INTO, // 251
	C_CREATUREFIGHT_ATTACKPOSE_OUTOF, // 252
	C_CREATUREFIGHT_BREATHER1,       // 253
	C_CREATUREFIGHT_CHAAARGE,        // 254
	C_CREATUREFIGHT_FINISHER1A,      // 255
	C_CREATUREFIGHT_FINISHER1B,      // 256
	C_CREATUREFIGHT_FINISHER1C,      // 257
	C_CREATUREFIGHT_GENERIC_ATTACK1, // 258
	C_CREATUREFIGHT_GENERIC_ATTACK2, // 259
	C_CREATUREFIGHT_HEAD_RECOIL_LEFT, // 260
	C_CREATUREFIGHT_HEAD_RECOIL_RIGHT, // 261
	C_CREATUREFIGHT_HEAD_RECOIL_UP,  // 262
	C_CREATUREFIGHT_KNOCKDOWN,       // 263
	C_CREATUREFIGHT_KNOCKEDDOWN,     // 264
	C_CREATUREFIGHT_LOOP_ATTACK1,    // 265
	C_CREATUREFIGHT_LOOP_ATTACK2,    // 266
	C_CREATUREFIGHT_LOOP_ATTACK3,    // 267
	C_CREATUREFIGHT_PRONE_ATTACK1,   // 268
	C_CREATUREFIGHT_PRONE_FLINCH_HEAD, // 269
	C_CREATUREFIGHT_PRONE_FLINCH_MID, // 270
	C_CREATUREFIGHT_PRONE_FLINCH_RIGHT, // 271
	C_CREATUREFIGHT_PRONE_GETUP,     // 272
	C_CREATUREFIGHT_PRONE_LOOP,      // 273
	C_CREATUREFIGHT_PRONE_SWITCH,    // 274
	C_CREATUREFIGHT_SHUFFLE_F_FAR,   // 275
	C_CREATUREFIGHT_SHUFFLE_F_NEAR,  // 276
	C_CREATUREFIGHT_STAGGERBACK_FLINCH, // 277
	C_CREATUREFIGHT_STATIC_FLINCH,   // 278
	C_CREATUREFIGHT_STRADDLEATTACK_INTO, // 279
	C_CREATUREFIGHT_STRADDLE_ATTACK1, // 280
	C_CREATUREFIGHT_STRADDLE_ATTACK2, // 281
	C_CREATUREFIGHT_STRADDLE_ATTACK3, // 282
	C_CREATUREFIGHT_STRADDLE_FLINCH_BACK, // 283
	C_CREATUREFIGHT_STRADDLE_FLINCH_FRONT, // 284
	C_CREATUREFIGHT_STRADDLE_FLINCH_SIDE, // 285
	C_CREATUREFIGHT_STRADDLE_GETUP,  // 286
	C_CREATUREFIGHT_STRADDLE_INTO,   // 287
	C_CREATUREFIGHT_STRADDLE_LOOP,   // 288
	C_CREATUREFIGHT_STRADDLE_SWITCH, // 289
	C_CREATUREFIGHT_STUNNED,         // 290
	C_CS_GROWING,                    // 291
	C_CS_INTRO_TURN_ROAR,            // 292
	C_CS_REACT,                      // 293
	C_CS_REACT1,                     // 294
	C_CS_SAD_INTO,                   // 295
	C_CS_SAD_LOOP,                   // 296
	C_CS_SAD_LOOP1,                  // 297
	C_CS_SAD_LOOP2,                  // 298
	C_CS_FIGHT_THREAT4,              // 299
	C_CS_R_STAND_LOOP,               // 300
	C_CS_R_STAND_LOOP_OUTOF,         // 301
	C_CS_MOVE_STAND,                 // 302
	C_CS_DANCE_BASIC,                // 303
	C_GO_LOOKTOSEA_LOOP,             // 304
	C_GO_INJURED_LOOP,               // 305
	C_L2OUTRO_VOLCANO_CREATE,        // 306
};

#define C_NUM_ANIMS                      307

#endif
