#pragma once
#ifndef __EPIC_WONDER_VISUAL_STAGES_ENUM_H__
#define __EPIC_WONDER_VISUAL_STAGES_ENUM_H__

// Last Saved,#2003-04-29 14:37:20#,"gwatts"

//*****************************************************************************
// ENUM Values: EPIC_WONDER_VISUAL_STAGES
//*****************************************************************************
enum     EPIC_WONDER_VISUAL_STAGES
{
	EPIC_WONDER_STAGE_1  = 0,
	EPIC_WONDER_STAGE_2,
	EPIC_WONDER_STAGE_3,
	EPIC_WONDER_STAGE_4,
	EPIC_WONDER_STAGE_5,
	EPIC_WONDER_STAGE_6,
	EPIC_WONDER_STAGE_7,
	EPIC_WONDER_STAGE_8,
	EPIC_WONDER_STAGE_9,
	EPIC_WONDER_STAGE_10,
	EPIC_WONDER_STAGE_START_BEAM,
	EPIC_WONDER_STAGE_END_BEAM,
	EPIC_WONDER_STAGE_LAST
};

enum EPIC_OBJECTS
{
	EPIC_OBJECT_VILLAGER = 0,
	EPIC_OBJECT_NYMPH,
	EPIC_WONDER_VILLAGER1,
	EPIC_WONDER_VILLAGER2,
	EPIC_WONDER_HACK_VILLAGER
};

#endif    // __EPIC_WONDER_VISUAL_STAGES_ENUM_H__