#ifndef __FORMATION_MOVEMENT_STAT_ENUM_H__
#define __FORMATION_MOVEMENT_STAT_ENUM_H__

enum     FORMATION_MOVEMENT_STAT
{
    FORMATION_MOVEMENT_STAT_AGENT_MASS,
    FORMATION_MOVEMENT_STAT_DECELLERATION_DIST,
    FORMATION_MOVEMENT_STAT_ACCELERATION_MAX,
    FORMATION_MOVEMENT_STAT_AGENT_SPEED_MAX,
    FORMATION_MOVEMENT_STAT_AGENT_SPEED_MIN,
    FORMATION_MOVEMENT_STAT_AGENT_CHARGE_SPEED,
    FORMATION_MOVEMENT_STAT_AGENT_FIGHTER_SPEED,
    FORMATION_MOVEMENT_STAT_PLATOON_SPEED,
    FORMATION_MOVEMENT_STAT_PLATOON_CHARGE_SPEED,
    FORMATION_MOVEMENT_STAT_POSITION_ACCURACY,
    FORMATION_MOVEMENT_STAT_FLIP_ANGLE,
    FORMATION_MOVEMENT_STAT_TURNS_BETWEEN_RANDOM_AGENT_SPEED_CHANGE,
    FORMATION_MOVEMENT_STAT_RANDOM_AGENT_SPEED_MAX_CHANGE,
	FORMATION_MOVEMENT_STAT_MOVE_BY_RANK_MODIFIER,
    FORMATION_MOVEMENT_STAT_LAST,
};

#endif    // __FORMATION_MOVEMENT_STAT_ENUM_H__