#ifndef _HAND_ICONS_ENUM_H_
#define _HAND_ICONS_ENUM_H_

enum HAND_ICON_TYPE
{
	HAND_ICON_NONE =0,
	HAND_ICON_RMB,
	HAND_ICON_LMB,
	HAND_ICON_BOTH,
	HAND_ICON_MMB,
	HAND_ICON_WHEEL_1,
	HAND_ICON_WHEEL_2,
	HAND_ICON_WHEEL_3,
	HAND_ICON_WHEEL_4,
	HAND_ICON_WHEEL_5,
	HAND_ICON_WHEEL_6,
	HAND_ICON_WHEEL_7,
	HAND_ICON_KEY,
	HAND_ICON_TYPE_LAST,
};

#endif //_HAND_ICONS_ENUM_H_