//////////////////////////////////////////////////////////////////////////
//	State Driven Group Types
//////////////////////////////////////////////////////////////////////////

#ifndef _STATEDRIVENGROUPTYPEENUM_H
#define _STATEDRIVENGROUPTYPEENUM_H

enum STATEDRIVEN_GROUP_TYPES
{
	STATEDRIVEN_GROUP_TYPES_DANCE_FOR_MANA_CIRCLE,
	STATEDRIVEN_GROUP_TYPES_DANCE_FOR_MANA_GRID,
	STATEDRIVEN_GROUP_TYPES_PROTEST_MARCH,
	STATEDRIVEN_GROUP_TYPES_PROTEST_PEACFUL,
	STATEDRIVEN_GROUP_TYPES_PROTEST_VIOLENT,
	STATEDRIVEN_GROUP_TYPES_SIT_FOR_STORY,
	STATEDRIVEN_GROUP_TYPES_DANCE_AROUND_CREATURE,
	STATEDRIVEN_GROUP_TYPES_DANCE_IN_FRONT_OF_CREATURE,
};	

#endif