#ifndef __TOWN_REQUIREMENT_ENUM_H__
#define __TOWN_REQUIREMENT_ENUM_H__


//*****************************************************************************
// ENUM Values: TOWN_REQUIREMENT
//*****************************************************************************
enum     TOWN_REQUIREMENT
{
	TOWN_REQUIREMENT_TO_GATHER_FOOD					= 0,
	TOWN_REQUIREMENT_TO_GROW_FOOD					= 1,
	TOWN_REQUIREMENT_TO_GATHER_WOOD					= 2,
	TOWN_REQUIREMENT_TO_GROW_WOOD					= 3,
	TOWN_REQUIREMENT_TO_GATHER_ORE					= 4,
	TOWN_REQUIREMENT_TO_SLEEP						= 5,
	TOWN_REQUIREMENT_TO_BREED						= 6,
	TOWN_REQUIREMENT_TO_BUILD_ABODES				= 7,
	TOWN_REQUIREMENT_TO_REPAIR						= 8	,
	TOWN_REQUIREMENT_TO_BUILD_CIVIC_BUILDINGS		= 9,
	TOWN_REQUIREMENT_FOR_DEFENSE					= 10,
	TOWN_REQUIREMENT_TO_ATTACK						= 11,
	TOWN_REQUIREMENT_TO_WORSHIP						= 12,
	TOWN_REQUIREMENT_FOR_FUNTIME					= 13,
	NUM_TOWN_REQUIREMENTS							= 14,
	INVALID_TOWN_REQUIREMENT						= 15,
};

#endif    // __TOWN_REQUIREMENT_ENUM_H__