#ifndef __VILLAGER_PAIRED_ACTION_ENUM_H__
#define __VILLAGER_PAIRED_ACTION_ENUM_H__

// Last Saved,#2005-08-18 14:41:36#,"Lionhead"

//*****************************************************************************
// ENUM Values: VILLAGER_PAIRED_ACTION
//*****************************************************************************
enum     VILLAGER_PAIRED_ACTION
{
    VILLAGER_PAIRED_ACTION_BREED                    =  0 ,
    VILLAGER_PAIRED_ACTION_PUB_FIGHT_1              =  1 ,
    VILLAGER_PAIRED_ACTION_PUB_FIGHT_2              =  2 ,
    VILLAGER_PAIRED_ACTION_PUB_FIGHT_3              =  3 ,
    VILLAGER_PAIRED_ACTION_PUB_CHAT_1               =  4 ,
    VILLAGER_PAIRED_ACTION_DANCE_CELEBRATE_1        =  5 ,
    VILLAGER_PAIRED_ACTION_DANCE_CELEBRATE_2        =  6 ,
    VILLAGER_PAIRED_ACTION_DANCE_WORSHIP_1          =  7 ,
    VILLAGER_PAIRED_ACTION_DANCE_WORSHIP_2          =  8 ,
    VILLAGER_PAIRED_ACTION_NYMPH_SEDUCE             =  9 ,
    VILLAGER_PAIRED_ACTION_ELOI_CHATTING_ANGRY      =  10 ,
    VILLAGER_PAIRED_ACTION_ELOI_BACK_PAT            =  11 ,
    VILLAGER_PAIRED_ACTION_PATERNITY_BIRTH_LOOP     =  12 ,
    VILLAGER_PAIRED_ACTION_PATERNITY_BIRTH_PAIRED   =  13 ,
    VILLAGER_PAIRED_ACTION_PATERNITY_BIRTH_COMFORT  =  14 ,
    VILLAGER_PAIRED_ACTION_PATERNITY_BIRTH_HUG      =  15 ,
    VILLAGER_PAIRED_ACTION_FAMILY_PARENTS_PRAYING   =  16 ,
    VILLAGER_PAIRED_ACTION_FAMILY_MOTHER_CHILD_HUG  =  17 ,
    VILLAGER_PAIRED_ACTION_PATERNITY_KISS1          =  18 ,
    VILLAGER_PAIRED_ACTION_PATERNITY_KISS2          =  19 ,
    VILLAGER_PAIRED_ACTION_ELOI_CHAT                =  20 ,
    VILLAGER_PAIRED_ACTION_LAST                     =  21 ,
};

#endif    // __VILLAGER_PAIRED_ACTION_ENUM_H__