#ifndef __VILLAGER_INFO_ENUM_H__
#define __VILLAGER_INFO_ENUM_H__

// Last Saved,#2005-08-05 16:41:50#,"Lionhead"

//*****************************************************************************
// ENUM Values: VILLAGER_INFO
//*****************************************************************************
enum     VILLAGER_INFO
{
    VILLAGER_INFO_FIRST                             =  0 ,
    VILLAGER_INFO_AZTEC_HOUSEWIFE_FEMALE            =  0 ,
    VILLAGER_INFO_AZTEC_FORESTER_MALE               =  1 ,
    VILLAGER_INFO_AZTEC_FISHERMAN_MALE              =  2 ,
    VILLAGER_INFO_AZTEC_FARMER_MALE                 =  3 ,
    VILLAGER_INFO_AZTEC_SHEPHERD_MALE               =  4 ,
    VILLAGER_INFO_AZTEC_LEADER_MALE                 =  5 ,
    VILLAGER_INFO_AZTEC_TRADER_MALE                 =  6 ,
    VILLAGER_INFO_JAPANESE_HOUSEWIFE_FEMALE         =  7 ,
    VILLAGER_INFO_JAPANESE_FORESTER_MALE            =  8 ,
    VILLAGER_INFO_JAPANESE_FISHERMAN_MALE           =  9 ,
    VILLAGER_INFO_JAPANESE_FARMER_MALE              =  10 ,
    VILLAGER_INFO_JAPANESE_SHEPHERD_MALE            =  11 ,
    VILLAGER_INFO_JAPANESE_LEADER_MALE              =  12 ,
    VILLAGER_INFO_JAPANESE_TRADER_MALE              =  13 ,
    VILLAGER_INFO_INDIGENOUS_HOUSEWIFE_FEMALE       =  14 ,
    VILLAGER_INFO_INDIGENOUS_FORESTER_MALE          =  15 ,
    VILLAGER_INFO_INDIGENOUS_FISHERMAN_MALE         =  16 ,
    VILLAGER_INFO_INDIGENOUS_FARMER_MALE            =  17 ,
    VILLAGER_INFO_INDIGENOUS_SHEPHERD_MALE          =  18 ,
    VILLAGER_INFO_INDIGENOUS_LEADER_MALE            =  19 ,
    VILLAGER_INFO_INDIGENOUS_TRADER_MALE            =  20 ,
    VILLAGER_INFO_GREEK_HOUSEWIFE_FEMALE            =  21 ,
    VILLAGER_INFO_GREEK_FORESTER_MALE               =  22 ,
    VILLAGER_INFO_GREEK_FISHERMAN_MALE              =  23 ,
    VILLAGER_INFO_GREEK_FARMER_MALE                 =  24 ,
    VILLAGER_INFO_GREEK_SHEPHERD_MALE               =  25 ,
    VILLAGER_INFO_GREEK_LEADER_MALE                 =  26 ,
    VILLAGER_INFO_GREEK_TRADER_MALE                 =  27 ,
    VILLAGER_INFO_NORSE_HOUSEWIFE_FEMALE            =  28 ,
    VILLAGER_INFO_NORSE_FORESTER_MALE               =  29 ,
    VILLAGER_INFO_NORSE_FISHERMAN_MALE              =  30 ,
    VILLAGER_INFO_NORSE_FARMER_MALE                 =  31 ,
    VILLAGER_INFO_NORSE_SHEPHERD_MALE               =  32 ,
    VILLAGER_INFO_NORSE_LEADER_MALE                 =  33 ,
    VILLAGER_INFO_NORSE_TRADER_MALE                 =  34 ,
    VILLAGER_INFO_ISLE_NYMPH                        =  35 ,
    VILLAGER_INFO_NYMPH                             =  36 ,
    VILLAGER_INFO_SIGVED                            =  37 ,
    VILLAGER_INFO_FENRICK                           =  38 ,
    VILLAGER_INFO_FENRICK_STRIPPED                  =  39 ,
    VILLAGER_INFO_FAIN                              =  40 ,
    VILLAGER_INFO_MERRYMAN1                         =  41 ,
    VILLAGER_INFO_MERRYMAN2                         =  42 ,
    VILLAGER_INFO_MERRYMAN3                         =  43 ,
    VILLAGER_INFO_MERRYMAN4                         =  44 ,
    VILLAGER_INFO_MERRYMAN5                         =  45 ,
    VILLAGER_INFO_MERRYMAN6                         =  46 ,
    VILLAGER_INFO_MERRYMAN7                         =  47 ,
    VILLAGER_INFO_MERRYMAN8                         =  48 ,
    VILLAGER_INFO_MERRYMAN9                         =  49 ,
    VILLAGER_INFO_MERRYMAN10                        =  50 ,
    VILLAGER_INFO_SMALL_NORSE_BOY                   =  51 ,
    VILLAGER_INFO_ROBIN_HOOD                        =  52 ,
    VILLAGER_INFO_DIMITRIOUS_ACOLYTE                =  53 ,
    VILLAGER_INFO_DIMITRIOUS                        =  54 ,
    VILLAGER_INFO_EURONYMOUS                        =  55 ,
    VILLAGER_INFO_AZTECMESSENGER                    =  56 ,
    VILLAGER_INFO_AZTECOILBARON                     =  57 ,
    VILLAGER_INFO_FELL                              =  58 ,
    VILLAGER_INFO_GREEK_JAILER                      =  59 ,
    VILLAGER_INFO_GREEK_BOATMASTER                  =  60 ,
    VILLAGER_INFO_YOUNG_MONK                        =  61 ,
    VILLAGER_INFO_TARANAGA                          =  62 ,
    VILLAGER_INFO_TEZOMOC                           =  63 ,
    VILLAGER_INFO_HIROKU                            =  64 ,
    VILLAGER_INFO_PROMETHEUS                        =  65 ,
    VILLAGER_INFO_INACHUS                           =  66 ,
    VILLAGER_INFO_EGYPTIAN_ASSASSIN                 =  67 ,
    VILLAGER_INFO_EGYPTIAN_SLAVE_DISGUISE           =  68 ,
    VILLAGER_INFO_SANURA                            =  69 ,
    VILLAGER_INFO_JAPANESE_BOATMASTER               =  70 ,
    VILLAGER_INFO_YUKA                              =  71 ,
    VILLAGER_INFO_OLD_MONK                          =  72 ,
    VILLAGER_INFO_BLACK_ANNIS                       =  73 ,
    VILLAGER_INFO_EGYPTIAN_MALE_A                   =  74 ,
    VILLAGER_INFO_EGYPTIAN_MALE_B                   =  75 ,
    VILLAGER_INFO_EGYPTIAN_FEMALE_A                 =  76 ,
    VILLAGER_INFO_EGYPTIAN_FEMALE_B                 =  77 ,
    VILLAGER_INFO_BAZMET                            =  78 ,
    VILLAGER_INFO_LAST                              =  79 ,
};

#endif    // __VILLAGER_INFO_ENUM_H__